16 call offer in service agent
2060-io/2060-service-agent pull request #18
Opened 2024-09-18 15:21 UTC by lotharking

2024-09-20 21:02 UTC, genaris requested changes

2024-09-20 21:02 UTC, genaris commented on src/events/MessageEvents.ts
> +        threadId: thread?.parentThreadId,
```
        threadId: thread?.id,
```

2024-09-20 21:02 UTC, genaris commented on src/events/MessageEvents.ts
> +        threadId: message.thread?.parentThreadId,
```
        threadId: message.thread?.id,
```

2024-09-20 21:02 UTC, genaris commented on src/events/MessageEvents.ts
> +        threadId: thread?.parentThreadId,
```suggestion
        threadId: thread?.id,
```

2024-09-23 15:22 UTC, lotharking commented on src/controllers/message/MessageService.ts
> +          callType: 'video',
fixed

2024-09-23 15:22 UTC, lotharking commented on src/model/messages/MessageType.ts
> +  CallOfferRequestMessage = 'call-offer-request',
fixed

2024-09-23 15:22 UTC, lotharking commented on src/model/messages/calls/CallParameters.ts
> +
fixed

2024-09-23 15:22 UTC, lotharking commented on src/events/MessageEvents.ts
> +        threadId: thread?.parentThreadId,
fixed, used to `thread?.threadId`

2024-09-23 15:23 UTC, lotharking commented on src/events/MessageEvents.ts
> +        threadId: thread?.parentThreadId,
fixed, used to thread?.threadId

2024-09-23 21:00 UTC, genaris approved these changes

2024-09-23 21:02 UTC, merged