feat: Refactor AppModule and Add Credential Management with Revocation Support
2060-io/2060-service-agent pull request #64
Opened 2024-12-16 20:46 UTC by lotharking

## Summary
#### Flow:
1. **Create a Credential**  
   - The user can request to create a credential.  
   - The library validates whether the credential can be created and ensures there isn't already one associated with the same hash.  
     - If a credential with the same hash exists, the credential will be revoked and associated with the new connection (from where the request is sent). A new credential request will then be initiated, ensuring the proper threadId is sent as part of the process
     - If valid, the credential creation request is sent.

2. **Rejection**  
   - Associates the thread and marks the credential as revoked (revoked only in terms of database nomenclature).  

3. **Acceptance**  
   - Associates the thread with the credential.

4. **Revocation**  
   - When a credential is revoked, it is marked as revoked in the database.

#### Additional Constraints:

- In all cases, a new record is created, ensuring indices do not overlap and atomicity is guaranteed during queries.  
- Records are expected to be assigned from `0` to the maximum value minus 1 (`-1`).  
  - Validation has confirmed that assignments from `1` to the maximum value fail.  
- Two revocation records will always remain available.  

## Changes
- A refactoring was implemented in the `AppModule` of the `nestjs-client` module. This was necessary because the original main module was not optimized for the recurrent use of variables, requiring multiple instantiations of the same variables. Modifying the `AppModule` and the configuration approach avoided redundancy when the module is instantiated. Compatibility with individual configurations was maintained.
- Support for credential management and revocation was implemented when configuring the `nestjs-client` module. The methods are controlled through the library, allowing for handling rejections and revocations as well.
- A demo was created to showcase how to use the `demo-dts`. As observed, the configuration required for complete credential management is minimal.

## Related Issues
- https://github.com/2060-io/2060-service-agent/issues/58

## Testing

## Checklist
- [x] I have commented on my code, especially in areas that are hard to understand.
- [x] I have added only changes relevant to the issue in question.
- [ ] I have added tests to confirm that my fix is effective or that my feature works as intended.
- [ ] I have modified existing tests as needed to accommodate my changes.
- [ ] I have flagged specific areas for further review, if necessary.
- [x] I have updated the documentation where necessary.

2025-01-15 13:18 UTC, genaris requested changes
Looking good. Some comments regarding the 'reference identifier' and supporting having more than a single credential type.

2025-01-15 13:18 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +   * It is recommended to call this method inside an `OnModuleInit` lifecycle hook to validate the existence
This is only for the specific case where a service is intended to issue only a single type of credential. It can be useful in those cases but in my opinion is too particular to name it as a general practice.

2025-01-15 13:18 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +  async create(
This method creates a credential definition (or "credential type", as we call it in Service Agent). We need to do a clear distinction between a credential type and the credentials issued using it as a base.

It might be more appropriate to use another module/service for that, but if we keep it in a single module for the sake of simplicity, we can maybe call this method `createType` or something related.

2025-01-15 13:18 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const [credential] = await this.apiClient.credentialTypes.getAll()
Again: this assumes that every service is supposed to define a single credential type. This is not correct.

If you want to know if a given credential type is already created, you should query credential types by name and version.

2025-01-15 19:29 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    records: Record<string, any>,
fix: added claims on issue method

2025-01-15 20:47 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const credentials = await this.apiClient.credentialTypes.getAll()
fix: add optional credentialDefinitionId on issue method

2025-01-15 20:57 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const [credential] = await this.apiClient.credentialTypes.getAll()
fix: implement selection credential by name and version

2025-01-15 21:36 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const hashIdentifier = options?.identifier ? this.hashIdentifier(options.identifier) : null
docs: update

2025-01-15 22:32 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +  async create(
fix: updated name method create

2025-01-15 22:34 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +   * It is recommended to call this method inside an `OnModuleInit` lifecycle hook to validate the existence
fix: updated for many credentials

2025-01-16 13:53 UTC, genaris requested changes

2025-01-16 13:53 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +   * - `autoRevocationEnabled` (optional, `boolean`): Whether automatic revocation is enabled (default false)
I think this should be more self-explanatory. Maybe something like: `revokeIfAlreadyIssued`

2025-01-16 13:53 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.entity.ts
> +  hashIdentifier?: string
I think this field should be renamed. `refIdHash`?

2025-01-16 16:32 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +      await this.saveCredential(credential.id, supportRevocation)
fix: name credentialType

2025-01-16 16:34 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.entity.ts
> +  hashIdentifier?: string
fix: name refIdHash

2025-01-16 16:38 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +   * - `autoRevocationEnabled` (optional, `boolean`): Whether automatic revocation is enabled (default false)
fix: add revokeIfAlreadyIssued

2025-01-16 16:46 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +   * - `refId` (optional, `string`): A unique identifier for the credential. If provided:
docs: update

2025-01-16 22:17 UTC, genaris requested changes

2025-01-16 22:17 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const cred = await this.credentialRepository.findOne({
A problem I see here is that you are using `connectionId` to identify the credential the event is related to. This is not correct, since you can issue multiple credentials to a single DIDComm connection.

The proper way you should identify a credential is by its threadId. Therefore, these `accept` and `reject` methods should only receive the threadId.

You can find the threadId in the response of the Message endpoint (the `id` correspond to the threadId).

2025-01-16 22:17 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    cred.revoked = true
A rejection by the user does not mean that a credential has been revoked. Maybe you can create a `status` field for the credential entity that covers the entire life cycle of a credential: probably offered, accepted, rejected and revoked may be enough.

2025-01-16 22:17 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const { name = 'Chatbot', version = '1.0', supportRevocation, maximumCredentialNumber } = options
I don't think it is correct to leave name and version as optional fields.

2025-01-16 22:17 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +        const invalidRegistries = await transaction.find(CredentialEntity, {
This logic is quite obscure to me. I don't think it will work.

I guess that somewhere (maybe another table/entity) you should keep track of the current revocation registry and index for each credential definition, and use that as the source of truth to assign the revocation registry/index of each issued credential, and tell if it is needed to create a new revocation registry or not.

2025-01-16 22:17 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    if (!cred) throw new Error(`Credencial with connectionId ${connectionId} not found.`)
```suggestion
    if (!cred) throw new Error(`Credential with connectionId ${connectionId} not found.`)
```

As explained before, threadId should be used instead of connectionId.

The connectionId is only needed to determine where to send the notification in case of a revocation.

2025-01-16 23:34 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +  private refIdHash(refId: string): string {
fix: change name refIdHash by hash

2025-01-16 23:37 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const { name = 'Chatbot', version = '1.0', supportRevocation, maximumCredentialNumber } = options
fix: remove name and version from optionals fields

2025-01-17 13:26 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const cred = await this.credentialRepository.findOne({
fix: implement revocation for all non-revoked credentials

2025-01-17 14:05 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +  private async saveCredentialType(
fix: updated to createRevocationRegistry

2025-01-17 15:20 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +  async accept(connectionId: string, threadId: string): Promise<void> {
fix: change name to handleAcceptance/handleRejection

2025-01-17 15:54 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    const cred = await this.credentialRepository.findOne({
fix: acept and reject only by thread

2025-01-17 16:22 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +    cred.revoked = true
fix: implement to CredentialStatus

2025-01-18 18:27 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.service.ts
> +        const invalidRegistries = await transaction.find(CredentialEntity, {
feat: Creation of the RevocationRegistryEntity for managing revocation records.

Please review this last change with special care. The `RevocationRegistryEntity` was created, and during its implementation, it was detected that the `threadId` returned by the `CredentialIssuanceMessage` was not being properly handled by the SA. As a solution, `GenericRecords` was used to retrieve it. Additionally, as you mentioned, the handling of credentials has been improved by dividing the entities.

2025-01-21 17:58 UTC, genaris requested changes

2025-01-21 17:58 UTC, genaris commented on packages/nestjs-client/src/credentials/revocation-registry.entity.ts
> +export class RevocationRegistryEntity {
Add credentialDefinitionId

2025-01-21 17:58 UTC, genaris commented on packages/nestjs-client/src/credentials/revocation-registry.entity.ts
> +  revocationRegistryIndex!: number
```suggestion
  currentIndex!: number
```

2025-01-21 17:58 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.entity.ts
> +  credentialDefinitionId!: string
add revocationRegistryIndex

2025-01-21 17:58 UTC, genaris commented on packages/nestjs-client/src/credentials/credential.service.ts
> +        .createQueryBuilder(RevocationRegistryEntity, 'registry')
add credentialDefinitionId to the filter

2025-01-21 21:51 UTC, lotharking commented on packages/nestjs-client/src/credentials/credential.entity.ts
> +  credentialDefinitionId!: string
fix: add credentialDefinitionId to revocation registry entity

2025-01-22 01:07 UTC, lotharking commented on packages/nestjs-client/src/credentials/revocation-registry.entity.ts
> +  revocationRegistryIndex!: number
fix: implemented currentIndex

2025-01-22 01:23 UTC, lotharking commented on packages/nestjs-client/src/credentials/revocation-registry.entity.ts
> +export class RevocationRegistryEntity {
fixed

2025-01-22 17:39 UTC, genaris approved these changes

2025-01-22 17:41 UTC, merged